name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - hydra-joblib-launcher==1.2.0
      - databricks-cli==0.17.0
      - omegaconf==2.3.0